# Generated by Django 4.2.1 on 2023-05-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAttachment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='post/%Y/%m'),
        ),
    ]
